print("This program calculates the avarage of two numbers")
number1 = float(input("Please enter number 1: "))
number2 = float(input("Please enter number 2: "))
print("The numbers are ", number1, " and ", number2)
print("The avarage is: ",(number1 + number2)/2)
